# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e6e533cbbddb82b0d4d42d029d5fff088606d446ac5819f4d6acbec201ebce27e5e6c7a4b14e1aa61eac1dc776b68afa7675985013e22ef8f25b2314132deeb

test:
  secret_key_base: f2abeda4f20f80cc890e5eae26b4adde0de10a46cb401787850dd42a0b17f35531f7dc36069d1f9415ce0d0070f66f025002ab72c3a3f19c28926acfc838a309

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
